### ISSUE TITLE
Question: Is there a safe way to use this as part of a multi-stage Dockerfile?

### ISSUE THREAD

**Issue by hrdwdmrbl** [andreasur/docker-ssh-agent#4]
Something like this maybe?

```Dockerfile
FROM nardeas/ssh-agent
FROM foo as intermediate

# do stuff that uses ssh-agent

FROM bar

COPY --from=intermediate /app /app

# do stuff without ssh-agent
```

I'm sorry if there is an obvious question, I'm a Docker n00b

**Comment by nardeas** [comment]
I suppose you could but I'm not sure how that would be helpful?

You would still need to add your keys to the ssh-agent somehow. You could have them as plaintext in your multi-stage Dockerfile and they wouldn't end up in the final image but in that case you could easily use any base image that runs ssh-agent. It would then be rather pointless to use this one.
