### ISSUE TITLE
Windows: no such file or directory

### ISSUE THREAD

**Issue by vialcollet** [andreasur/docker-ssh-agent#8]
Hi
When I try to load a key, it fails with :
`standard_init_linux.go:175: exec user process caused "no such file or directory"`

I am using Docker Toolbox on Windows 7.

I can confirm I have a valid id_rsa file with LF line endings (as this can be an issue) located in my home/.ssh folder.

**Comment by nardeas** [comment]
What command you use to launch the container?

**Comment by nardeas** [comment]
This is not really meant for Windows

**Comment by vialcollet** [comment]
Ok point taken. Thanks
